/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedBrowseRouteImport } from './routes/_authed/browse'
import { Route as AuthedTripsRouteImport } from './routes/_authed/trips'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthedProfileUserIdRouteImport } from './routes/_authed/profile.$userId'
import { Route as AuthedMessagesThreadTypeThreadIdRouteImport } from './routes/_authed/messages.$threadType.$threadId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowseRoute = AuthedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsRoute = AuthedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedProfileUserIdRoute = AuthedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesThreadTypeThreadIdRoute =
  AuthedMessagesThreadTypeThreadIdRouteImport.update({
    id: '/messages/$threadType/$threadId',
    path: '/messages/$threadType/$threadId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/browse': typeof AuthedBrowseRoute
  '/trips': typeof AuthedTripsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/messages/$threadType/$threadId': typeof AuthedMessagesThreadTypeThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/browse': typeof AuthedBrowseRoute
  '/trips': typeof AuthedTripsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/messages/$threadType/$threadId': typeof AuthedMessagesThreadTypeThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authed/browse': typeof AuthedBrowseRoute
  '/_authed/trips': typeof AuthedTripsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/profile/$userId': typeof AuthedProfileUserIdRoute
  '/_authed/messages/$threadType/$threadId': typeof AuthedMessagesThreadTypeThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/trips'
    | '/login'
    | '/signup'
    | '/profile/$userId'
    | '/messages/$threadType/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/trips'
    | '/login'
    | '/signup'
    | '/profile/$userId'
    | '/messages/$threadType/$threadId'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_authed/browse'
    | '/_authed/trips'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_authed/'
    | '/_authed/profile/$userId'
    | '/_authed/messages/$threadType/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browse': {
      id: '/_authed/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthedBrowseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips': {
      id: '/_authed/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthedTripsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/profile/$userId': {
      id: '/_authed/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthedProfileUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages/$threadType/$threadId': {
      id: '/_authed/messages/$threadType/$threadId'
      path: '/messages/$threadType/$threadId'
      fullPath: '/messages/$threadType/$threadId'
      preLoaderRoute: typeof AuthedMessagesThreadTypeThreadIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBrowseRoute: typeof AuthedBrowseRoute
  AuthedTripsRoute: typeof AuthedTripsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProfileUserIdRoute: typeof AuthedProfileUserIdRoute
  AuthedMessagesThreadTypeThreadIdRoute: typeof AuthedMessagesThreadTypeThreadIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBrowseRoute: AuthedBrowseRoute,
  AuthedTripsRoute: AuthedTripsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProfileUserIdRoute: AuthedProfileUserIdRoute,
  AuthedMessagesThreadTypeThreadIdRoute: AuthedMessagesThreadTypeThreadIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
